#version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - WordPressbis:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
    build: requirements/nginx/
    env_file: .env
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build: requirements/mariadb/
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
      - WordPressbis:/var/www/html
    networks:
      - inception
    build: requirements/wordpress/
    depends_on:
      - mariadb
    restart: always
    expose: 
      - "9000"
    ports:
      - "9000:9000"


networks:
  inception:
    name : inception
    driver : bridge


volumes:
  db:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/aceralin/data/db'

  WordPressbis:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aceralin/data/wordpress'

