#Image de base
FROM debian:bullseye


#Ajoute les dependances ou outils necessaires (commandes shell)
RUN 

#copie des fichiers ou repetoires dans l image
COPY ./nginx.conf /etc/nginx/nginx.conf

#definit les variables d environnement


#expose des ports pour acceder au conteneur
EXPOSE 3306

#commande a executer lors de la construction : 
CMD 